CREATE TABLE mytable(
  id SERIAL PRIMARY KEY, 
  name      VARCHAR(25)
  ,type      VARCHAR(9)
  ,january   VARCHAR(9)
  ,february  VARCHAR(9)
  ,march     VARCHAR(9)
  ,april     VARCHAR(9)
  ,may       VARCHAR(9)
  ,june      VARCHAR(9)
  ,july      VARCHAR(9)
  ,august    VARCHAR(9)
  ,september VARCHAR(9)
  ,october   VARCHAR(9)
  ,november  VARCHAR(9)
  ,december  VARCHAR(9)
  ,img_src   VARCHAR(105)
  ,favourite VARCHAR(5)
);
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('asparagus','vegetable','out','out','out','out','coming_in','at_best','at_best','out','out','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('aubergine','vegetable','out','out','out','out','coming_in','at_best','at_best','at_best','at_best','at_best','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('basil','vegetable','out','out','out','out','out','coming_in','at_best','at_best','out','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('beetroot','vegetable','at_best','out','out','out','out','out','at_best','at_best','at_best','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('broccoli','vegetable','out','out','out','out','out','out','coming_in','at_best','at_best','at_best','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('brussels sprouts','vegetable','at_best','at_best','at_best','out','out','out','out','out','out','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('cabbage','vegetable','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('carrot','vegetable','out','out','out','out','coming_in','at_best','at_best','at_best','at_best','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('cauliflower','vegetable','at_best','at_best','at_best','at_best','out','out','out','out','out','out','out','coming_in','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('cavolo_nero','vegetable','out','out','out','out','out','coming_in','at_best','at_best','at_best','at_best','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('celeriac','vegetable','at_best','at_best','at_best','at_best','out','out','out','out','at_best','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('celery','vegetable','at_best','at_best','out','out','out','out','coming_in','at_best','at_best','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('chicory','vegetable','at_best','at_best','at_best','out','out','out','out','out','out','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('courgette','vegetable','out','out','out','out','out','at_best','at_best','at_best','at_best','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('courgette_flower','vegetable','out','out','out','out','out','at_best','at_best','at_best','out','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('fennel_bulb','vegetable','out','out','out','out','out','at_best','at_best','at_best','at_best','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('garlic','vegetable','out','out','out','out','out','coming_in','at_best','at_best','at_best','at_best','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('globe_artichoke','vegetable','out','out','out','out','coming_in','at_best','at_best','at_best','at_best','at_best','at_best','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('jerusalem_artichoke','vegetable','at_best','at_best','at_best','out','out','out','out','out','out','coming_in','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('kale','vegetable','at_best','at_best','out','out','out','out','out','out','coming_in','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('kohlrabi','vegetable','out','out','out','out','out','out','coming_in','at_best','at_best','at_best','at_best','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('lamb''s_lettuce','vegetable','out','out','out','out','at_best','at_best','at_best','at_best','at_best','at_best','at_best','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('leek','vegetable','at_best','at_best','at_best','out','out','out','out','out','at_best','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('lettuce','vegetable','out','out','out','coming_in','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('marrow','vegetable','out','out','out','out','out','out','coming_in','at_best','at_best','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('new_potatoes','vegetable','out','out','out','at_best','at_best','at_best','at_best','out','out','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('pak_choi','vegetable','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('parsnip','vegetable','at_best','at_best','at_best','out','out','out','out','out','at_best','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('peas','vegetable','out','out','out','coming_in','at_best','at_best','at_best','at_best','at_best','at_best','at_best','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('pepper','vegetable','out','coming_in','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('potato','vegetable','out','out','coming_in','at_best','at_best','at_best','at_best','out','out','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('pumpkin','vegetable','out','out','out','out','out','out','out','out','coming_in','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('purple_sprouting_broccoli','vegetable','coming_in','at_best','at_best','at_best','out','out','out','out','out','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('radicchio','vegetable','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('radish','vegetable','out','out','out','coming_in','at_best','at_best','at_best','at_best','at_best','at_best','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('runner_bean','vegetable','out','out','out','out','out','at_best','at_best','at_best','at_best','at_best','at_best','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('salsify','vegetable','at_best','out','out','out','out','out','out','out','coming_in','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('samphire','vegetable','out','out','out','out','out','out','at_best','at_best','out','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('spinach','vegetable','out','out','coming_in','at_best','at_best','at_best','at_best','at_best','at_best','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('spring_greens','vegetable','out','out','coming_in','at_best','at_best','at_best','out','out','out','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('swede','vegetable','at_best','at_best','out','out','out','out','out','out','out','coming_in','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('sweet_potato','vegetable','at_best','at_best','at_best','out','out','out','out','out','out','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('sweetcorn','vegetable','out','out','out','out','out','out','out','coming_in','at_best','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('swiss_chard','vegetable','out','out','out','out','out','out','at_best','at_best','at_best','at_best','at_best','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('turnip','vegetable','at_best','at_best','out','out','out','out','out','out','out','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('watercress','vegetable','out','out','coming_in','at_best','at_best','at_best','at_best','at_best','at_best','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('apple','fruit','at_best','at_best','out','out','out','out','out','out','at_best','at_best','at_best','at_best','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('apricot','fruit','out','out','out','out','at_best','at_best','at_best','at_best','at_best','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('banana','fruit','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('blackberry','fruit','out','out','out','out','out','out','coming_in','at_best','at_best','at_best','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('blackcurrants','fruit','out','out','out','out','coming_in','at_best','at_best','out','out','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('bramley_apple','fruit','at_best','at_best','at_best','out','out','out','out','out','out','out','coming_in','at_best','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('cherry','fruit','out','out','out','out','out','coming_in','at_best','out','out','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('clementine','fruit','at_best','at_best','out','out','out','out','out','out','out','out','at_best','at_best','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('cranberry','fruit','out','out','out','out','out','out','out','out','out','at_best','at_best','at_best','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('damson','fruit','out','out','out','out','out','out','out','coming_in','at_best','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('date','fruit','at_best','out','out','out','out','out','out','out','out','coming_in','at_best','at_best','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('elderberries','fruit','out','out','out','out','out','out','out','at_best','at_best','at_best','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('fig','fruit','out','out','out','out','out','out','coming_in','at_best','at_best','at_best','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('gooseberry','fruit','out','out','out','out','coming_in','at_best','at_best','at_best','at_best','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('grapefruit','fruit','at_best','at_best','at_best','at_best','at_best','out','out','out','out','out','out','at_best','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('lemon','fruit','at_best','at_best','at_best','out','out','out','out','out','out','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('nectarine','fruit','out','out','out','out','at_best','at_best','at_best','at_best','at_best','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('orange','fruit','at_best','at_best','at_best','out','out','out','out','out','out','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('peach','fruit','out','out','out','out','out','out','coming_in','at_best','at_best','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('pear','fruit','at_best','out','out','out','out','out','out','out','at_best','at_best','at_best','at_best','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('plum','fruit','out','out','out','out','out','out','out','coming_in','at_best','at_best','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('pomegranate','fruit','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('quince','fruit','out','out','out','out','out','out','out','out','coming_in','at_best','at_best','at_best','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('raspberry','fruit','out','out','out','out','out','coming_in','at_best','at_best','at_best','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('redcurrant','fruit','out','out','out','out','out','coming_in','at_best','at_best','at_best','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('rhubarb','fruit','at_best','at_best','at_best','at_best','at_best','at_best','out','out','out','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('strawberry','fruit','out','out','out','out','coming_in','at_best','at_best','at_best','at_best','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('tomato','fruit','out','out','out','out','coming_in','at_best','at_best','at_best','at_best','at_best','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('watermelon','fruit','out','out','out','out','out','coming_in','at_best','at_best','out','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
