DROP DATABASE IF EXISTS feg_sql_test;
CREATE DATABASE feg_sql_test;

CREATE TABLE mytable(
   name      VARCHAR(25) NOT NULL PRIMARY KEY
  ,type      VARCHAR(9)
  ,january   VARCHAR(9)
  ,february  VARCHAR(7)
  ,march     VARCHAR(9)
  ,april     VARCHAR(9)
  ,may       VARCHAR(9)
  ,june      VARCHAR(9)
  ,july      VARCHAR(9)
  ,august    VARCHAR(9)
  ,september VARCHAR(9)
  ,october   VARCHAR(9)
  ,november  VARCHAR(7)
  ,december  VARCHAR(9)
  ,img_src   VARCHAR(105)
  ,favourite VARCHAR(5)
);
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('basil','vegetable','out','out','out','out','out','coming_in','at_best','at_best','out','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('broccoli','vegetable','out','out','out','out','out','out','coming_in','at_best','at_best','at_best','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('cabbage','vegetable','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('cauliflower','vegetable','at_best','at_best','at_best','at_best','out','out','out','out','out','out','out','coming_in','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('celeriac','vegetable','at_best','at_best','at_best','at_best','out','out','out','out','at_best','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('chicory','vegetable','at_best','at_best','at_best','out','out','out','out','out','out','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('courgette_flower','vegetable','out','out','out','out','out','at_best','at_best','at_best','out','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('garlic','vegetable','out','out','out','out','out','coming_in','at_best','at_best','at_best','at_best','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('jerusalem_artichoke','vegetable','at_best','at_best','at_best','out','out','out','out','out','out','coming_in','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('kohlrabi','vegetable','out','out','out','out','out','out','coming_in','at_best','at_best','at_best','at_best','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('leek','vegetable','at_best','at_best','at_best','out','out','out','out','out','at_best','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('marrow','vegetable','out','out','out','out','out','out','coming_in','at_best','at_best','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('pak_choi','vegetable','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('peas','vegetable','out','out','out','coming_in','at_best','at_best','at_best','at_best','at_best','at_best','at_best','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('potato','vegetable','out','out','coming_in','at_best','at_best','at_best','at_best','out','out','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('purple_sprouting_broccoli','vegetable','coming_in','at_best','at_best','at_best','out','out','out','out','out','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('radish','vegetable','out','out','out','coming_in','at_best','at_best','at_best','at_best','at_best','at_best','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('salsify','vegetable','at_best','out','out','out','out','out','out','out','coming_in','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('spinach','vegetable','out','out','coming_in','at_best','at_best','at_best','at_best','at_best','at_best','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('swede','vegetable','at_best','at_best','out','out','out','out','out','out','out','coming_in','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('sweetcorn','vegetable','out','out','out','out','out','out','out','coming_in','at_best','out','out','out','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('turnip','vegetable','at_best','at_best','out','out','out','out','out','out','out','at_best','at_best','at_best','https://c.pxhere.com/photos/06/4a/vegetables_season_leek_apple_useful_health_pumpkin_cabbage-673328.jpg!d','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('apple','fruit','at_best','at_best','out','out','out','out','out','out','at_best','at_best','at_best','at_best','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('banana','fruit','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','at_best','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('blackcurrants','fruit','out','out','out','out','coming_in','at_best','at_best','out','out','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('cherry','fruit','out','out','out','out','out','coming_in','at_best','out','out','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('cranberry','fruit','out','out','out','out','out','out','out','out','out','at_best','at_best','at_best','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('date','fruit','at_best','out','out','out','out','out','out','out','out','coming_in','at_best','at_best','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('fig','fruit','out','out','out','out','out','out','coming_in','at_best','at_best','at_best','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('grapefruit','fruit','at_best','at_best','at_best','at_best','at_best','out','out','out','out','out','out','at_best','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('nectarine','fruit','out','out','out','out','at_best','at_best','at_best','at_best','at_best','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('peach','fruit','out','out','out','out','out','out','coming_in','at_best','at_best','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('plum','fruit','out','out','out','out','out','out','out','coming_in','at_best','at_best','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('quince','fruit','out','out','out','out','out','out','out','out','coming_in','at_best','at_best','at_best','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('raspberry','fruit','out','out','out','out','out','coming_in','at_best','at_best','at_best','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('rhubarb','fruit','at_best','at_best','at_best','at_best','at_best','at_best','out','out','out','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
INSERT INTO mytable(name,type,january,february,march,april,may,june,july,august,september,october,november,december,img_src,favourite) VALUES ('watermelon','fruit','out','out','out','out','out','coming_in','at_best','at_best','out','out','out','out','https://pixnio.com/free-images/2017/09/19/2017-09-19-06-59-45-1100x738.jpg','FALSE');
